os: linux
dist: bionic
language: cpp
compiler:
    # FIXME: For now, building with Clang is disabled because the STP built with
    # it hits an assertion failure during some tests. We should sort this out
    # eventually and file the bug against STP or Clang whichever is appropriate,
    # but for now it is easier to just reduce the number of configs we test
    # anyway.
    # - clang
    - gcc
env:
    ###########################################################################
    # Configurations
    #
    # Each line in the "env" section represents a set of environment variables
    # passed to a build. Thus each line represents a different build
    # configuration.
    ###########################################################################

    # Check a subset of the matrix of:
    #   LLVM  : {9}
    #   SOLVERS : {STP}
    #   DISABLE_ASSERTIONS: {0}
    #   ENABLE_OPTIMIZED: {1}

    # Check KLEE CMake build
    - LLVM_VERSION=9 SOLVERS=STP DISABLE_ASSERTIONS=0 ENABLE_OPTIMIZED=1

addons:
  apt:
    sources:
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-7
    - g++-7
    - libcap-dev
    - libselinux1-dev
    - cmake
    - libsqlite3-dev
    - bison
    - flex
    - libboost-all-dev
    - python3
    - python3-setuptools
    - python3-pip
    - perl
    - zlib1g-dev
    - minisat

cache: apt
before_install:
    - sudo apt-get update
    ###########################################################################
    # Set up out of source build directory
    ###########################################################################
    - export SRC_DIR=`pwd`
    - cd ../
    - mkdir build
    - cd build/
    - export BUILD_DIR=`pwd`
    ###########################################################################
    # Install stuff
    ###########################################################################
    # Install LLVM and the LLVM bitcode compiler we require to build KLEE
    - ${SRC_DIR}/.travis/install-llvm-and-runtime-compiler.sh
script:
    # Build uclibc
    - ${SRC_DIR}/.travis/uclibc.sh
    # Test uclibc integration with KLEE
    - ${SRC_DIR}/.travis/klee.sh
